### ISSUE TITLE
AppleScript doesn't work with the `-l` flag during terminal start

### ISSUE THREAD

**Issue by jcmorrow** [jcmorrow/dotfiles#11]
With the changes in https://github.com/jcmorrow/dotfiles/compare/jm-spotify-js I get the following results:

From running the script manually:

```
▶ ~/.zsh/functions/spotify-compact-status
Vice City (feat. Black Hippy) by Jay Rock
```

Upon starting up a new terminal session:

```
/Users/josh/.zsh/functions/spotify-compact-status:2: permission denied: //
```

Side question (this may reveal a lot of ignorance on my part), why is this script getting executed when a terminal session is started? (and also, why does it happen even if I am not in tmux?)

🚨 @gabebw 🚨

**Comment by gabebw** [comment]
>Side question (this may reveal a lot of ignorance on my part), why is this script getting executed when a terminal session is started? (and also, why does it happen even if I am not in tmux?)

Aha, I see what's going on. This chunk of code runs everything in `~/.zsh/functions/`:

https://github.com/jcmorrow/dotfiles/blob/4dd1ec4d035c60ab04299f01f805e032a45c6c06/zshrc#L5-L7

I put my script in `~/bin`, where it's not autoexecuted.

**Comment by gabebw** [comment]
I should explain a little more.

`source SCRIPT` is different from actually running it. `source SCRIPT` is as if you copied each line in `SCRIPT` into your shell. It ignores shebangs (the first line, that starts with `#!`).

So here's what happens:

* zsh runs line 1 of `spotify-compact-status`: `#!/usr/bin/osascript -l JavaScript`, which is just a comment line. So far so good.
* zsh runs line 2 of `spotify-compact-status`: `// vim: textwidth=0 filetype=javascript`, which...I guess is trying to run a file named `/` in the root `/` directory? Maybe? Whatever it's doing, it's not working, and it crashes.

**Comment by jcmorrow** [comment]
@gabebw I was working on something unrelated subject-wise, but running into exactly the same problem today. I figured it out on my own, came here to comment, and saw you sorting out my confusion! 😂 

I've never put much thought into how the files in `zsh/functions` differed in how they were loaded and what that meant for executing them, but now it makes a lot of sense. 

Thanks! 🎉

**Comment by jcmorrow** [comment]
Also an interesting effect of this is that things defined in `zsh/functions` cannot be `:Dispatch`ed from vim because the background terminal that `:Dispatch` opens does not load my `.zshrc`, but it does get the `$PATH` from my current shell (or at least, I'm guessing that's how it works), so things inside of `/bin` can be run with `:Dispatch`.
